# Generated by Django 4.1.3 on 2023-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_blog', '0005_websitesetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
